	/*** YOLO layer 1:
	 * - Convolution: With downsampling
	 * - Activation:  8 * 416 * 416
	 * - Weight:      8 * 64 * 3 * 3
	 */
{
	// Layer 1: Parameter
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG0_OFFSET,
			0x0001a03a);
	// Layer 1: Parameter 2: { output_channels, input_channels }
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG1_OFFSET,
			0x00040008);
	// Layer 1: act write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG2_OFFSET,
			0x05000000);
	// Layer 1: act read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG3_OFFSET,
			0x05000000);
	// Layer 1: weight write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG4_OFFSET,
			0x00000000);
	// Layer 1: weight read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG5_OFFSET,
			0x00000000);
	// Layer 1: weight write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG6_OFFSET,
			0x00001200);
	// Layer 1: bias write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG7_OFFSET,
			0x04000000);
	// Layer 1: bias read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG8_OFFSET,
			0x04000000);
	// Layer 1: bias write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG9_OFFSET,
			0x00000040);
	// Layer 1: ddr write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG10_OFFSET,
			0x052a4000);
}

	/*** YOLO layer 2:
	 * - Convolution: With downsampling
	 * - Activation:  64 * 416 * 416
	 * - Weight:      64 * 64 * 3 * 3
	 */
{
	// Layer 2: Parameter
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG0_OFFSET,
			0x0001a078);
	// Layer 2: Parameter 2: { output_channels, input_channels }
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG1_OFFSET,
			0x00040040);
	// Layer 2: act write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG2_OFFSET,
			0x052a4000);
	// Layer 2: act read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG3_OFFSET,
			0x052a4000);
	// Layer 2: weight write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG4_OFFSET,
			0x00002400);
	// Layer 2: weight read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG5_OFFSET,
			0x00002400);
	// Layer 2: weight write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG6_OFFSET,
			0x00009000);
	// Layer 2: bias write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG7_OFFSET,
			0x04000100);
	// Layer 2: bias read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG8_OFFSET,
			0x04000100);
	// Layer 2: bias write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG9_OFFSET,
			0x00000040);
	// Layer 2: ddr write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG10_OFFSET,
			0x067c4000);
}

	/*** YOLO layer 3:
	 * - Convolution: With downsampling
	 * - Activation:  64 * 208 * 208
	 * - Weight:      64 * 64 * 3 * 3
	 */
{
	// Layer 3: Parameter
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG0_OFFSET,
			0x0000d038);
	// Layer 3: Parameter 2: { output_channels, input_channels }
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG1_OFFSET,
			0x00040040);
	// Layer 3: act write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG2_OFFSET,
			0x067c4000);
	// Layer 3: act read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG3_OFFSET,
			0x067c4000);
	// Layer 3: weight write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG4_OFFSET,
			0x00014400);
	// Layer 3: weight read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG5_OFFSET,
			0x00014400);
	// Layer 3: weight write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG6_OFFSET,
			0x00009000);
	// Layer 3: bias write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG7_OFFSET,
			0x04000200);
	// Layer 3: bias read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG8_OFFSET,
			0x04000200);
	// Layer 3: bias write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG9_OFFSET,
			0x00000040);
	// Layer 3: ddr write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG10_OFFSET,
			0x06d0c000);
}

	/*** YOLO layer 4:
	 * - Convolution: With downsampling
	 * - Activation:  64 * 208 * 208
	 * - Weight:      64 * 64 * 3 * 3
	 */
{
	// Layer 4: Parameter
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG0_OFFSET,
			0x0000d078);
	// Layer 4: Parameter 2: { output_channels, input_channels }
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG1_OFFSET,
			0x00040040);
	// Layer 4: act write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG2_OFFSET,
			0x06d0c000);
	// Layer 4: act read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG3_OFFSET,
			0x06d0c000);
	// Layer 4: weight write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG4_OFFSET,
			0x00026400);
	// Layer 4: weight read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG5_OFFSET,
			0x00026400);
	// Layer 4: weight write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG6_OFFSET,
			0x00009000);
	// Layer 4: bias write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG7_OFFSET,
			0x04000300);
	// Layer 4: bias read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG8_OFFSET,
			0x04000300);
	// Layer 4: bias write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG9_OFFSET,
			0x00000040);
	// Layer 4: ddr write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG10_OFFSET,
			0x07254000);
}

	/*** YOLO layer 5:
	 * - Convolution: With downsampling
	 * - Activation:  64 * 104 * 104
	 * - Weight:      64 * 128 * 3 * 3
	 */
{
	// Layer 5: Parameter
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG0_OFFSET,
			0x00006838);
	// Layer 5: Parameter 2: { output_channels, input_channels }
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG1_OFFSET,
			0x00080040);
	// Layer 5: act write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG2_OFFSET,
			0x07254000);
	// Layer 5: act read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG3_OFFSET,
			0x07254000);
	// Layer 5: weight write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG4_OFFSET,
			0x00038400);
	// Layer 5: weight read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG5_OFFSET,
			0x00038400);
	// Layer 5: weight write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG6_OFFSET,
			0x00012000);
	// Layer 5: bias write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG7_OFFSET,
			0x04000400);
	// Layer 5: bias read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG8_OFFSET,
			0x04000400);
	// Layer 5: bias write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG9_OFFSET,
			0x00000080);
	// Layer 5: ddr write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG10_OFFSET,
			0x073a6000);
}

	/*** YOLO layer 6:
	 * - Convolution: With downsampling
	 * - Activation:  128 * 104 * 104
	 * - Weight:      128 * 64 * 3 * 3
	 */
{
	// Layer 6: Parameter
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG0_OFFSET,
			0x00006839);
	// Layer 6: Parameter 2: { output_channels, input_channels }
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG1_OFFSET,
			0x00040080);
	// Layer 6: act write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG2_OFFSET,
			0x073a6000);
	// Layer 6: act read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG3_OFFSET,
			0x073a6000);
	// Layer 6: weight write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG4_OFFSET,
			0x0005c400);
	// Layer 6: weight read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG5_OFFSET,
			0x0005c400);
	// Layer 6: weight write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG6_OFFSET,
			0x00002000);
	// Layer 6: bias write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG7_OFFSET,
			0x04000600);
	// Layer 6: bias read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG8_OFFSET,
			0x04000600);
	// Layer 6: bias write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG9_OFFSET,
			0x00000040);
	// Layer 6: ddr write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG10_OFFSET,
			0x0764a000);
}

	/*** YOLO layer 7:
	 * - Convolution: With downsampling
	 * - Activation:  64 * 104 * 104
	 * - Weight:      64 * 128 * 3 * 3
	 */
{
	// Layer 7: Parameter
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG0_OFFSET,
			0x00006838);
	// Layer 7: Parameter 2: { output_channels, input_channels }
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG1_OFFSET,
			0x00080040);
	// Layer 7: act write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG2_OFFSET,
			0x0764a000);
	// Layer 7: act read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG3_OFFSET,
			0x0764a000);
	// Layer 7: weight write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG4_OFFSET,
			0x00060400);
	// Layer 7: weight read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG5_OFFSET,
			0x00060400);
	// Layer 7: weight write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG6_OFFSET,
			0x00012000);
	// Layer 7: bias write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG7_OFFSET,
			0x04000700);
	// Layer 7: bias read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG8_OFFSET,
			0x04000700);
	// Layer 7: bias write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG9_OFFSET,
			0x00000080);
	// Layer 7: ddr write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG10_OFFSET,
			0x0779c000);
}

	/*** YOLO layer 8:
	 * - Convolution: With downsampling
	 * - Activation:  128 * 104 * 104
	 * - Weight:      128 * 128 * 3 * 3
	 */
{
	// Layer 8: Parameter
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG0_OFFSET,
			0x00006878);
	// Layer 8: Parameter 2: { output_channels, input_channels }
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG1_OFFSET,
			0x00080080);
	// Layer 8: act write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG2_OFFSET,
			0x0779c000);
	// Layer 8: act read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG3_OFFSET,
			0x0779c000);
	// Layer 8: weight write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG4_OFFSET,
			0x00084400);
	// Layer 8: weight read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG5_OFFSET,
			0x00084400);
	// Layer 8: weight write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG6_OFFSET,
			0x00024000);
	// Layer 8: bias write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG7_OFFSET,
			0x04000900);
	// Layer 8: bias read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG8_OFFSET,
			0x04000900);
	// Layer 8: bias write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG9_OFFSET,
			0x00000080);
	// Layer 8: ddr write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG10_OFFSET,
			0x07a40000);
}

	/*** YOLO layer 9:
	 * - Convolution: With downsampling
	 * - Activation:  128 * 52 * 52
	 * - Weight:      128 * 256 * 3 * 3
	 */
{
	// Layer 9: Parameter
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG0_OFFSET,
			0x00003438);
	// Layer 9: Parameter 2: { output_channels, input_channels }
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG1_OFFSET,
			0x00100080);
	// Layer 9: act write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG2_OFFSET,
			0x07a40000);
	// Layer 9: act read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG3_OFFSET,
			0x07a40000);
	// Layer 9: weight write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG4_OFFSET,
			0x000cc400);
	// Layer 9: weight read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG5_OFFSET,
			0x000cc400);
	// Layer 9: weight write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG6_OFFSET,
			0x00048000);
	// Layer 9: bias write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG7_OFFSET,
			0x04000b00);
	// Layer 9: bias read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG8_OFFSET,
			0x04000b00);
	// Layer 9: bias write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG9_OFFSET,
			0x00000100);
	// Layer 9: ddr write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG10_OFFSET,
			0x07ae9000);
}

	/*** YOLO layer 10:
	 * - Convolution: With downsampling
	 * - Activation:  256 * 52 * 52
	 * - Weight:      256 * 128 * 3 * 3
	 */
{
	// Layer 10: Parameter
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG0_OFFSET,
			0x00003439);
	// Layer 10: Parameter 2: { output_channels, input_channels }
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG1_OFFSET,
			0x00080100);
	// Layer 10: act write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG2_OFFSET,
			0x07ae9000);
	// Layer 10: act read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG3_OFFSET,
			0x07ae9000);
	// Layer 10: weight write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG4_OFFSET,
			0x0015c400);
	// Layer 10: weight read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG5_OFFSET,
			0x0015c400);
	// Layer 10: weight write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG6_OFFSET,
			0x00008000);
	// Layer 10: bias write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG7_OFFSET,
			0x04000f00);
	// Layer 10: bias read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG8_OFFSET,
			0x04000f00);
	// Layer 10: bias write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG9_OFFSET,
			0x00000080);
	// Layer 10: ddr write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG10_OFFSET,
			0x07c3b000);
}

	/*** YOLO layer 11:
	 * - Convolution: With downsampling
	 * - Activation:  128 * 52 * 52
	 * - Weight:      128 * 256 * 3 * 3
	 */
{
	// Layer 11: Parameter
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG0_OFFSET,
			0x00003438);
	// Layer 11: Parameter 2: { output_channels, input_channels }
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG1_OFFSET,
			0x00100080);
	// Layer 11: act write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG2_OFFSET,
			0x07c3b000);
	// Layer 11: act read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG3_OFFSET,
			0x07c3b000);
	// Layer 11: weight write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG4_OFFSET,
			0x0016c400);
	// Layer 11: weight read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG5_OFFSET,
			0x0016c400);
	// Layer 11: weight write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG6_OFFSET,
			0x00048000);
	// Layer 11: bias write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG7_OFFSET,
			0x04001100);
	// Layer 11: bias read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG8_OFFSET,
			0x04001100);
	// Layer 11: bias write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG9_OFFSET,
			0x00000100);
	// Layer 11: ddr write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG10_OFFSET,
			0x07ce4000);
}

	/*** YOLO layer 12:
	 * - Convolution: With downsampling
	 * - Activation:  256 * 52 * 52
	 * - Weight:      256 * 256 * 3 * 3
	 */
{
	// Layer 12: Parameter
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG0_OFFSET,
			0x00003478);
	// Layer 12: Parameter 2: { output_channels, input_channels }
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG1_OFFSET,
			0x00100100);
	// Layer 12: act write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG2_OFFSET,
			0x07ce4000);
	// Layer 12: act read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG3_OFFSET,
			0x07ce4000);
	// Layer 12: weight write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG4_OFFSET,
			0x001fc400);
	// Layer 12: weight read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG5_OFFSET,
			0x001fc400);
	// Layer 12: weight write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG6_OFFSET,
			0x00090000);
	// Layer 12: bias write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG7_OFFSET,
			0x04001500);
	// Layer 12: bias read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG8_OFFSET,
			0x04001500);
	// Layer 12: bias write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG9_OFFSET,
			0x00000100);
	// Layer 12: ddr write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG10_OFFSET,
			0x07e36000);
}

	/*** YOLO layer 13:
	 * - Convolution: With downsampling
	 * - Activation:  256 * 26 * 26
	 * - Weight:      256 * 512 * 3 * 3
	 */
{
	// Layer 13: Parameter
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG0_OFFSET,
			0x00001a38);
	// Layer 13: Parameter 2: { output_channels, input_channels }
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG1_OFFSET,
			0x00200100);
	// Layer 13: act write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG2_OFFSET,
			0x07e36000);
	// Layer 13: act read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG3_OFFSET,
			0x07e36000);
	// Layer 13: weight write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG4_OFFSET,
			0x0031c400);
	// Layer 13: weight read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG5_OFFSET,
			0x0031c400);
	// Layer 13: weight write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG6_OFFSET,
			0x00120000);
	// Layer 13: bias write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG7_OFFSET,
			0x04001900);
	// Layer 13: bias read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG8_OFFSET,
			0x04001900);
	// Layer 13: bias write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG9_OFFSET,
			0x00000200);
	// Layer 13: ddr write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG10_OFFSET,
			0x07e8a800);
}

	/*** YOLO layer 14:
	 * - Convolution: With downsampling
	 * - Activation:  512 * 26 * 26
	 * - Weight:      512 * 256 * 3 * 3
	 */
{
	// Layer 14: Parameter
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG0_OFFSET,
			0x00001a39);
	// Layer 14: Parameter 2: { output_channels, input_channels }
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG1_OFFSET,
			0x00100200);
	// Layer 14: act write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG2_OFFSET,
			0x07e8a800);
	// Layer 14: act read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG3_OFFSET,
			0x07e8a800);
	// Layer 14: weight write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG4_OFFSET,
			0x0055c400);
	// Layer 14: weight read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG5_OFFSET,
			0x0055c400);
	// Layer 14: weight write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG6_OFFSET,
			0x00020000);
	// Layer 14: bias write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG7_OFFSET,
			0x04002100);
	// Layer 14: bias read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG8_OFFSET,
			0x04002100);
	// Layer 14: bias write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG9_OFFSET,
			0x00000100);
	// Layer 14: ddr write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG10_OFFSET,
			0x07f33800);
}

	/*** YOLO layer 15:
	 * - Convolution: With downsampling
	 * - Activation:  256 * 26 * 26
	 * - Weight:      256 * 512 * 3 * 3
	 */
{
	// Layer 15: Parameter
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG0_OFFSET,
			0x00001a38);
	// Layer 15: Parameter 2: { output_channels, input_channels }
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG1_OFFSET,
			0x00200100);
	// Layer 15: act write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG2_OFFSET,
			0x07f33800);
	// Layer 15: act read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG3_OFFSET,
			0x07f33800);
	// Layer 15: weight write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG4_OFFSET,
			0x0059c400);
	// Layer 15: weight read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG5_OFFSET,
			0x0059c400);
	// Layer 15: weight write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG6_OFFSET,
			0x00120000);
	// Layer 15: bias write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG7_OFFSET,
			0x04002500);
	// Layer 15: bias read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG8_OFFSET,
			0x04002500);
	// Layer 15: bias write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG9_OFFSET,
			0x00000200);
	// Layer 15: ddr write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG10_OFFSET,
			0x07f88000);
}

	/*** YOLO layer 16:
	 * - Convolution: With downsampling
	 * - Activation:  512 * 26 * 26
	 * - Weight:      512 * 256 * 3 * 3
	 */
{
	// Layer 16: Parameter
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG0_OFFSET,
			0x00001a39);
	// Layer 16: Parameter 2: { output_channels, input_channels }
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG1_OFFSET,
			0x00100200);
	// Layer 16: act write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG2_OFFSET,
			0x07f88000);
	// Layer 16: act read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG3_OFFSET,
			0x07f88000);
	// Layer 16: weight write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG4_OFFSET,
			0x007dc400);
	// Layer 16: weight read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG5_OFFSET,
			0x007dc400);
	// Layer 16: weight write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG6_OFFSET,
			0x00020000);
	// Layer 16: bias write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG7_OFFSET,
			0x04002d00);
	// Layer 16: bias read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG8_OFFSET,
			0x04002d00);
	// Layer 16: bias write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG9_OFFSET,
			0x00000100);
	// Layer 16: ddr write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG10_OFFSET,
			0x08031000);
}

	/*** YOLO layer 17:
	 * - Convolution: With downsampling
	 * - Activation:  256 * 26 * 26
	 * - Weight:      256 * 512 * 3 * 3
	 */
{
	// Layer 17: Parameter
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG0_OFFSET,
			0x00001a38);
	// Layer 17: Parameter 2: { output_channels, input_channels }
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG1_OFFSET,
			0x00200100);
	// Layer 17: act write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG2_OFFSET,
			0x08031000);
	// Layer 17: act read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG3_OFFSET,
			0x08031000);
	// Layer 17: weight write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG4_OFFSET,
			0x0081c400);
	// Layer 17: weight read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG5_OFFSET,
			0x0081c400);
	// Layer 17: weight write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG6_OFFSET,
			0x00120000);
	// Layer 17: bias write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG7_OFFSET,
			0x04003100);
	// Layer 17: bias read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG8_OFFSET,
			0x04003100);
	// Layer 17: bias write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG9_OFFSET,
			0x00000200);
	// Layer 17: ddr write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG10_OFFSET,
			0x08085800);
}

	/*** YOLO layer 18:
	 * - Convolution: With downsampling
	 * - Activation:  512 * 26 * 26
	 * - Weight:      512 * 512 * 3 * 3
	 */
{
	// Layer 18: Parameter
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG0_OFFSET,
			0x00001a78);
	// Layer 18: Parameter 2: { output_channels, input_channels }
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG1_OFFSET,
			0x00200200);
	// Layer 18: act write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG2_OFFSET,
			0x08085800);
	// Layer 18: act read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG3_OFFSET,
			0x08085800);
	// Layer 18: weight write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG4_OFFSET,
			0x00a5c400);
	// Layer 18: weight read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG5_OFFSET,
			0x00a5c400);
	// Layer 18: weight write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG6_OFFSET,
			0x00240000);
	// Layer 18: bias write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG7_OFFSET,
			0x04003900);
	// Layer 18: bias read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG8_OFFSET,
			0x04003900);
	// Layer 18: bias write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG9_OFFSET,
			0x00000200);
	// Layer 18: ddr write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG10_OFFSET,
			0x0812e800);
}

	/*** YOLO layer 19:
	 * - Convolution: With downsampling
	 * - Activation:  512 * 13 * 13
	 * - Weight:      512 * 1024 * 3 * 3
	 */
{
	// Layer 19: Parameter
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG0_OFFSET,
			0x00000d38);
	// Layer 19: Parameter 2: { output_channels, input_channels }
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG1_OFFSET,
			0x00400200);
	// Layer 19: act write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG2_OFFSET,
			0x0812e800);
	// Layer 19: act read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG3_OFFSET,
			0x0812e800);
	// Layer 19: weight write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG4_OFFSET,
			0x00edc400);
	// Layer 19: weight read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG5_OFFSET,
			0x00edc400);
	// Layer 19: weight write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG6_OFFSET,
			0x00480000);
	// Layer 19: bias write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG7_OFFSET,
			0x04004100);
	// Layer 19: bias read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG8_OFFSET,
			0x04004100);
	// Layer 19: bias write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG9_OFFSET,
			0x00000400);
	// Layer 19: ddr write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG10_OFFSET,
			0x08158c00);
}

	/*** YOLO layer 20:
	 * - Convolution: With downsampling
	 * - Activation:  1024 * 13 * 13
	 * - Weight:      1024 * 512 * 3 * 3
	 */
{
	// Layer 20: Parameter
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG0_OFFSET,
			0x00000d39);
	// Layer 20: Parameter 2: { output_channels, input_channels }
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG1_OFFSET,
			0x00200400);
	// Layer 20: act write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG2_OFFSET,
			0x08158c00);
	// Layer 20: act read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG3_OFFSET,
			0x08158c00);
	// Layer 20: weight write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG4_OFFSET,
			0x017dc400);
	// Layer 20: weight read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG5_OFFSET,
			0x017dc400);
	// Layer 20: weight write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG6_OFFSET,
			0x00080000);
	// Layer 20: bias write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG7_OFFSET,
			0x04005100);
	// Layer 20: bias read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG8_OFFSET,
			0x04005100);
	// Layer 20: bias write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG9_OFFSET,
			0x00000200);
	// Layer 20: ddr write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG10_OFFSET,
			0x081ad400);
}

	/*** YOLO layer 21:
	 * - Convolution: With downsampling
	 * - Activation:  512 * 13 * 13
	 * - Weight:      512 * 1024 * 3 * 3
	 */
{
	// Layer 21: Parameter
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG0_OFFSET,
			0x00000d38);
	// Layer 21: Parameter 2: { output_channels, input_channels }
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG1_OFFSET,
			0x00400200);
	// Layer 21: act write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG2_OFFSET,
			0x081ad400);
	// Layer 21: act read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG3_OFFSET,
			0x081ad400);
	// Layer 21: weight write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG4_OFFSET,
			0x018dc400);
	// Layer 21: weight read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG5_OFFSET,
			0x018dc400);
	// Layer 21: weight write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG6_OFFSET,
			0x00480000);
	// Layer 21: bias write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG7_OFFSET,
			0x04005900);
	// Layer 21: bias read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG8_OFFSET,
			0x04005900);
	// Layer 21: bias write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG9_OFFSET,
			0x00000400);
	// Layer 21: ddr write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG10_OFFSET,
			0x081d7800);
}

	/*** YOLO layer 22:
	 * - Convolution: With downsampling
	 * - Activation:  1024 * 13 * 13
	 * - Weight:      1024 * 512 * 3 * 3
	 */
{
	// Layer 22: Parameter
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG0_OFFSET,
			0x00000d39);
	// Layer 22: Parameter 2: { output_channels, input_channels }
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG1_OFFSET,
			0x00200400);
	// Layer 22: act write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG2_OFFSET,
			0x081d7800);
	// Layer 22: act read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG3_OFFSET,
			0x081d7800);
	// Layer 22: weight write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG4_OFFSET,
			0x021dc400);
	// Layer 22: weight read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG5_OFFSET,
			0x021dc400);
	// Layer 22: weight write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG6_OFFSET,
			0x00080000);
	// Layer 22: bias write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG7_OFFSET,
			0x04006900);
	// Layer 22: bias read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG8_OFFSET,
			0x04006900);
	// Layer 22: bias write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG9_OFFSET,
			0x00000200);
	// Layer 22: ddr write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG10_OFFSET,
			0x0822c000);
}

	/*** YOLO layer 23:
	 * - Convolution: With downsampling
	 * - Activation:  512 * 13 * 13
	 * - Weight:      512 * 1024 * 3 * 3
	 */
{
	// Layer 23: Parameter
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG0_OFFSET,
			0x00000d38);
	// Layer 23: Parameter 2: { output_channels, input_channels }
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG1_OFFSET,
			0x00400200);
	// Layer 23: act write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG2_OFFSET,
			0x0822c000);
	// Layer 23: act read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG3_OFFSET,
			0x0822c000);
	// Layer 23: weight write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG4_OFFSET,
			0x022dc400);
	// Layer 23: weight read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG5_OFFSET,
			0x022dc400);
	// Layer 23: weight write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG6_OFFSET,
			0x00480000);
	// Layer 23: bias write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG7_OFFSET,
			0x04007100);
	// Layer 23: bias read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG8_OFFSET,
			0x04007100);
	// Layer 23: bias write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG9_OFFSET,
			0x00000400);
	// Layer 23: ddr write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG10_OFFSET,
			0x08256400);
}

	/*** YOLO layer 24:
	 * - Convolution: With downsampling
	 * - Activation:  1024 * 13 * 13
	 * - Weight:      1024 * 1024 * 3 * 3
	 */
{
	// Layer 24: Parameter
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG0_OFFSET,
			0x00000d38);
	// Layer 24: Parameter 2: { output_channels, input_channels }
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG1_OFFSET,
			0x00400400);
	// Layer 24: act write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG2_OFFSET,
			0x08256400);
	// Layer 24: act read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG3_OFFSET,
			0x08256400);
	// Layer 24: weight write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG4_OFFSET,
			0x02bdc400);
	// Layer 24: weight read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG5_OFFSET,
			0x02bdc400);
	// Layer 24: weight write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG6_OFFSET,
			0x00900000);
	// Layer 24: bias write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG7_OFFSET,
			0x04008100);
	// Layer 24: bias read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG8_OFFSET,
			0x04008100);
	// Layer 24: bias write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG9_OFFSET,
			0x00000400);
	// Layer 24: ddr write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG10_OFFSET,
			0x082aac00);
}

	/*** YOLO layer 25:
	 * - Convolution: With downsampling
	 * - Activation:  1024 * 13 * 13
	 * - Weight:      1024 * 1024 * 3 * 3
	 */
{
	// Layer 25: Parameter
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG0_OFFSET,
			0x00000d38);
	// Layer 25: Parameter 2: { output_channels, input_channels }
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG1_OFFSET,
			0x00400400);
	// Layer 25: act write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG2_OFFSET,
			0x082aac00);
	// Layer 25: act read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG3_OFFSET,
			0x082aac00);
	// Layer 25: weight write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG4_OFFSET,
			0x03ddc400);
	// Layer 25: weight read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG5_OFFSET,
			0x03ddc400);
	// Layer 25: weight write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG6_OFFSET,
			0x00900000);
	// Layer 25: bias write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG7_OFFSET,
			0x04009100);
	// Layer 25: bias read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG8_OFFSET,
			0x04009100);
	// Layer 25: bias write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG9_OFFSET,
			0x00000400);
	// Layer 25: ddr write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG10_OFFSET,
			0x082ff400);
}

	/*** YOLO layer 26:
	 * - Convolution: With downsampling
	 * - Activation:  1024 * 13 * 13
	 * - Weight:      1024 * 1024 * 3 * 3
	 */
{
	// Layer 26: Parameter
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG0_OFFSET,
			0x00000d38);
	// Layer 26: Parameter 2: { output_channels, input_channels }
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG1_OFFSET,
			0x00400400);
	// Layer 26: act write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG2_OFFSET,
			0x082ff400);
	// Layer 26: act read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG3_OFFSET,
			0x082ff400);
	// Layer 26: weight write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG4_OFFSET,
			0x04fdc400);
	// Layer 26: weight read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG5_OFFSET,
			0x04fdc400);
	// Layer 26: weight write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG6_OFFSET,
			0x00900000);
	// Layer 26: bias write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG7_OFFSET,
			0x0400a100);
	// Layer 26: bias read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG8_OFFSET,
			0x0400a100);
	// Layer 26: bias write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG9_OFFSET,
			0x00000400);
	// Layer 26: ddr write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG10_OFFSET,
			0x08353c00);
}

	/*** YOLO layer 27:
	 * - Convolution: With downsampling
	 * - Activation:  1024 * 13 * 13
	 * - Weight:      1024 * 256 * 3 * 3
	 */
{
	// Layer 27: Parameter
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG0_OFFSET,
			0x000a0d29);
	// Layer 27: Parameter 2: { output_channels, input_channels }
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG1_OFFSET,
			0x00100400);
	// Layer 27: act write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG2_OFFSET,
			0x08353c00);
	// Layer 27: act read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG3_OFFSET,
			0x08353c00);
	// Layer 27: weight write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG4_OFFSET,
			0x061dc400);
	// Layer 27: weight read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG5_OFFSET,
			0x061dc400);
	// Layer 27: weight write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG6_OFFSET,
			0x00040000);
	// Layer 27: bias write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG7_OFFSET,
			0x0400b100);
	// Layer 27: bias read address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG8_OFFSET,
			0x0400b100);
	// Layer 27: bias write length: Number of elements.
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG9_OFFSET,
			0x00000100);
	// Layer 27: ddr write address
	CONFIG_SYSTOLIC_CONV_mWriteReg(
			XPAR_CONFIG_SYSTOLIC_CONV_0_S00_AXI_BASEADDR, CONFIG_SYSTOLIC_CONV_S00_AXI_SLV_REG10_OFFSET,
			0x083a8400);
}

